version: '3.8'

volumes:
  postgres_data:

services:
  nginx:
    restart: always
    image: nginx:latest
    expose:
      - 8080
    ports:
      - "80:8080"
    volumes:
      - ./static:/srv/www/yamdb_final/static
      - ./media:/srv/www/yamdb_final/media
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    volumes:
      - ./yamdb_final:/srv/www/<project>
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
